version: '3'

services:
  web:
    tty: true
    build: .
    restart: always
    ports:
      - 8002:8002
  # db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: test